#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanioNc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CL")]
	public partial class ComDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Inserttbl_Access(tbl_Access instance);
    partial void Updatetbl_Access(tbl_Access instance);
    partial void Deletetbl_Access(tbl_Access instance);
    #endregion
		
		public ComDataDataContext() : 
				base(global::CompanioNc.Properties.Settings.Default.CLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ComDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Access> tbl_Access
		{
			get
			{
				return this.GetTable<tbl_Access>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudALL_by_uid")]
		public ISingleResult<sp_cloudALL_by_uidResult> sp_cloudALL_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudALL_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudDEN_by_uid")]
		public ISingleResult<sp_cloudDEN_by_uidResult> sp_cloudDEN_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudDEN_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudDIS_by_uid")]
		public ISingleResult<sp_cloudDIS_by_uidResult> sp_cloudDIS_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudDIS_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudlab_by_uid")]
		public ISingleResult<sp_cloudlab_by_uidResult> sp_cloudlab_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudlab_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudmed_by_uid")]
		public ISingleResult<sp_cloudmed_by_uidResult> sp_cloudmed_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudmed_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudOP_by_uid")]
		public ISingleResult<sp_cloudOP_by_uidResult> sp_cloudOP_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudOP_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudREH_by_uid")]
		public ISingleResult<sp_cloudREH_by_uidResult> sp_cloudREH_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudREH_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudSCH_R_by_uid")]
		public ISingleResult<sp_cloudSCH_R_by_uidResult> sp_cloudSCH_R_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudSCH_R_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudSCH_U_by_uid")]
		public ISingleResult<sp_cloudSCH_U_by_uidResult> sp_cloudSCH_U_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudSCH_U_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cloudTCM_by_uid")]
		public ISingleResult<sp_cloudTCM_by_uidResult> sp_cloudTCM_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_cloudTCM_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_CBC_by_uid")]
		public ISingleResult<sp_labdata_CBC_by_uidResult> sp_labdata_CBC_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_CBC_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_DM_by_uid")]
		public ISingleResult<sp_labdata_DM_by_uidResult> sp_labdata_DM_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_DM_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_DRUG_by_uid")]
		public ISingleResult<sp_labdata_DRUG_by_uidResult> sp_labdata_DRUG_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_DRUG_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_hepa_by_uid")]
		public ISingleResult<sp_labdata_hepa_by_uidResult> sp_labdata_hepa_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_hepa_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_OTHER_by_uid")]
		public ISingleResult<sp_labdata_OTHER_by_uidResult> sp_labdata_OTHER_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_OTHER_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_labdata_UA_by_uid")]
		public ISingleResult<sp_labdata_UA_by_uidResult> sp_labdata_UA_by_uid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string u)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u);
			return ((ISingleResult<sp_labdata_UA_by_uidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_querytable")]
		public ISingleResult<sp_querytableResult> sp_querytable()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_querytableResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insert_access")]
		public int sp_insert_access([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDATE", DbType="Date")] System.Nullable<System.DateTime> sDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VIST", DbType="NVarChar(50)")] string vIST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RMNO", DbType="TinyInt")] System.Nullable<byte> rMNO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nr", DbType="TinyInt")] System.Nullable<byte> nr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="Bit")] System.Nullable<bool> sTATUS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sDATE, vIST, rMNO, nr, uid, cname, sTATUS);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Access")]
	public partial class tbl_Access : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Access_id;
		
		private System.DateTime _SDATE;
		
		private string _VIST;
		
		private byte _RMNO;
		
		private byte _Nr;
		
		private string _uid;
		
		private string _cname;
		
		private bool _STATUS;
		
		private System.DateTime _access_time;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccess_idChanging(long value);
    partial void OnAccess_idChanged();
    partial void OnSDATEChanging(System.DateTime value);
    partial void OnSDATEChanged();
    partial void OnVISTChanging(string value);
    partial void OnVISTChanged();
    partial void OnRMNOChanging(byte value);
    partial void OnRMNOChanged();
    partial void OnNrChanging(byte value);
    partial void OnNrChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void OncnameChanging(string value);
    partial void OncnameChanged();
    partial void OnSTATUSChanging(bool value);
    partial void OnSTATUSChanged();
    partial void Onaccess_timeChanging(System.DateTime value);
    partial void Onaccess_timeChanged();
    #endregion
		
		public tbl_Access()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Access_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Access_id
		{
			get
			{
				return this._Access_id;
			}
			set
			{
				if ((this._Access_id != value))
				{
					this.OnAccess_idChanging(value);
					this.SendPropertyChanging();
					this._Access_id = value;
					this.SendPropertyChanged("Access_id");
					this.OnAccess_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIST", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VIST
		{
			get
			{
				return this._VIST;
			}
			set
			{
				if ((this._VIST != value))
				{
					this.OnVISTChanging(value);
					this.SendPropertyChanging();
					this._VIST = value;
					this.SendPropertyChanged("VIST");
					this.OnVISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMNO", DbType="TinyInt NOT NULL")]
		public byte RMNO
		{
			get
			{
				return this._RMNO;
			}
			set
			{
				if ((this._RMNO != value))
				{
					this.OnRMNOChanging(value);
					this.SendPropertyChanging();
					this._RMNO = value;
					this.SendPropertyChanged("RMNO");
					this.OnRMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr", DbType="TinyInt NOT NULL")]
		public byte Nr
		{
			get
			{
				return this._Nr;
			}
			set
			{
				if ((this._Nr != value))
				{
					this.OnNrChanging(value);
					this.SendPropertyChanging();
					this._Nr = value;
					this.SendPropertyChanged("Nr");
					this.OnNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this.OncnameChanging(value);
					this.SendPropertyChanging();
					this._cname = value;
					this.SendPropertyChanged("cname");
					this.OncnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit NOT NULL")]
		public bool STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_time", DbType="DateTime NOT NULL")]
		public System.DateTime access_time
		{
			get
			{
				return this._access_time;
			}
			set
			{
				if ((this._access_time != value))
				{
					this.Onaccess_timeChanging(value);
					this.SendPropertyChanging();
					this._access_time = value;
					this.SendPropertyChanged("access_time");
					this.Onaccess_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_cloudALL_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private string _source_name;
		
		private string _remark;
		
		private string _drug_name;
		
		public sp_cloudALL_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(50)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drug_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string drug_name
		{
			get
			{
				return this._drug_name;
			}
			set
			{
				if ((this._drug_name != value))
				{
					this._drug_name = value;
				}
			}
		}
	}
	
	public partial class sp_cloudDEN_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private string _source_name;
		
		private string _diagnosis;
		
		private string _op_name;
		
		private string _loca;
		
		private System.Nullable<byte> _amt;
		
		public sp_cloudDEN_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(50)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this._diagnosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_name", DbType="NVarChar(100)")]
		public string op_name
		{
			get
			{
				return this._op_name;
			}
			set
			{
				if ((this._op_name != value))
				{
					this._op_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loca", DbType="NVarChar(50)")]
		public string loca
		{
			get
			{
				return this._loca;
			}
			set
			{
				if ((this._loca != value))
				{
					this._loca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="TinyInt")]
		public System.Nullable<byte> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this._amt = value;
				}
			}
		}
	}
	
	public partial class sp_cloudDIS_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private System.DateTime _EDATE;
		
		private string _source_name;
		
		private string _dep;
		
		private string _diagnosis;
		
		public sp_cloudDIS_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDATE", DbType="Date NOT NULL")]
		public System.DateTime EDATE
		{
			get
			{
				return this._EDATE;
			}
			set
			{
				if ((this._EDATE != value))
				{
					this._EDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep", DbType="NVarChar(50)")]
		public string dep
		{
			get
			{
				return this._dep;
			}
			set
			{
				if ((this._dep != value))
				{
					this._dep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(50)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this._diagnosis = value;
				}
			}
		}
	}
	
	public partial class sp_cloudlab_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _source;
		
		private string _o;
		
		public sp_cloudlab_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="NVarChar(10)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this._source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_cloudmed_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _source;
		
		private string _diag;
		
		private string _o;
		
		public sp_cloudmed_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="NVarChar(10)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this._source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diag", DbType="NVarChar(500)")]
		public string diag
		{
			get
			{
				return this._diag;
			}
			set
			{
				if ((this._diag != value))
				{
					this._diag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(4000)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_cloudOP_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private string _source_name;
		
		private string _dep;
		
		private string _diagnosis;
		
		private string _op_name;
		
		private string _loca;
		
		private System.Nullable<byte> _amt;
		
		public sp_cloudOP_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep", DbType="NVarChar(50)")]
		public string dep
		{
			get
			{
				return this._dep;
			}
			set
			{
				if ((this._dep != value))
				{
					this._dep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(50)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this._diagnosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_name", DbType="NVarChar(100)")]
		public string op_name
		{
			get
			{
				return this._op_name;
			}
			set
			{
				if ((this._op_name != value))
				{
					this._op_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loca", DbType="NVarChar(50)")]
		public string loca
		{
			get
			{
				return this._loca;
			}
			set
			{
				if ((this._loca != value))
				{
					this._loca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="TinyInt")]
		public System.Nullable<byte> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this._amt = value;
				}
			}
		}
	}
	
	public partial class sp_cloudREH_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private string _source_name;
		
		private string _diagnosis;
		
		private string _type;
		
		private string _loca;
		
		private string _curegrade;
		
		private System.Nullable<byte> _amt;
		
		public sp_cloudREH_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(10)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this._diagnosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loca", DbType="NVarChar(50)")]
		public string loca
		{
			get
			{
				return this._loca;
			}
			set
			{
				if ((this._loca != value))
				{
					this._loca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curegrade", DbType="NVarChar(50)")]
		public string curegrade
		{
			get
			{
				return this._curegrade;
			}
			set
			{
				if ((this._curegrade != value))
				{
					this._curegrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="TinyInt")]
		public System.Nullable<byte> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this._amt = value;
				}
			}
		}
	}
	
	public partial class sp_cloudSCH_R_by_uidResult
	{
		
		private string _drug_name;
		
		private string _YM;
		
		private System.Nullable<byte> _visit_n;
		
		private System.Nullable<byte> _clinic_n;
		
		private System.Nullable<short> _t_dose;
		
		private System.Nullable<short> _t_DDD;
		
		public sp_cloudSCH_R_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drug_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string drug_name
		{
			get
			{
				return this._drug_name;
			}
			set
			{
				if ((this._drug_name != value))
				{
					this._drug_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YM", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string YM
		{
			get
			{
				return this._YM;
			}
			set
			{
				if ((this._YM != value))
				{
					this._YM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_n", DbType="TinyInt")]
		public System.Nullable<byte> visit_n
		{
			get
			{
				return this._visit_n;
			}
			set
			{
				if ((this._visit_n != value))
				{
					this._visit_n = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clinic_n", DbType="TinyInt")]
		public System.Nullable<byte> clinic_n
		{
			get
			{
				return this._clinic_n;
			}
			set
			{
				if ((this._clinic_n != value))
				{
					this._clinic_n = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dose", DbType="SmallInt")]
		public System.Nullable<short> t_dose
		{
			get
			{
				return this._t_dose;
			}
			set
			{
				if ((this._t_dose != value))
				{
					this._t_dose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_DDD", DbType="SmallInt")]
		public System.Nullable<short> t_DDD
		{
			get
			{
				return this._t_DDD;
			}
			set
			{
				if ((this._t_DDD != value))
				{
					this._t_DDD = value;
				}
			}
		}
	}
	
	public partial class sp_cloudSCH_U_by_uidResult
	{
		
		private string _drugname;
		
		private System.DateTime _SDATE;
		
		private string _STIME;
		
		private string _clinic;
		
		private System.Nullable<short> _t_dose;
		
		private System.Nullable<short> _t_DDD;
		
		public sp_cloudSCH_U_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drugname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string drugname
		{
			get
			{
				return this._drugname;
			}
			set
			{
				if ((this._drugname != value))
				{
					this._drugname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STIME", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string STIME
		{
			get
			{
				return this._STIME;
			}
			set
			{
				if ((this._STIME != value))
				{
					this._STIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clinic", DbType="NVarChar(10)")]
		public string clinic
		{
			get
			{
				return this._clinic;
			}
			set
			{
				if ((this._clinic != value))
				{
					this._clinic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dose", DbType="SmallInt")]
		public System.Nullable<short> t_dose
		{
			get
			{
				return this._t_dose;
			}
			set
			{
				if ((this._t_dose != value))
				{
					this._t_dose = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_DDD", DbType="SmallInt")]
		public System.Nullable<short> t_DDD
		{
			get
			{
				return this._t_DDD;
			}
			set
			{
				if ((this._t_DDD != value))
				{
					this._t_DDD = value;
				}
			}
		}
	}
	
	public partial class sp_cloudTCM_by_uidResult
	{
		
		private System.DateTime _SDATE;
		
		private string _source_name;
		
		private string _diagnosis;
		
		private string _base;
		
		private string _effect;
		
		private string _dosing;
		
		private System.Nullable<byte> _days;
		
		private string _type;
		
		private System.Nullable<short> _amt;
		
		public sp_cloudTCM_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date NOT NULL")]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100)")]
		public string source_name
		{
			get
			{
				return this._source_name;
			}
			set
			{
				if ((this._source_name != value))
				{
					this._source_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagnosis", DbType="NVarChar(50)")]
		public string diagnosis
		{
			get
			{
				return this._diagnosis;
			}
			set
			{
				if ((this._diagnosis != value))
				{
					this._diagnosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="base", Storage="_base", DbType="NVarChar(50)")]
		public string @base
		{
			get
			{
				return this._base;
			}
			set
			{
				if ((this._base != value))
				{
					this._base = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect", DbType="NVarChar(50)")]
		public string effect
		{
			get
			{
				return this._effect;
			}
			set
			{
				if ((this._effect != value))
				{
					this._effect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosing", DbType="NVarChar(50)")]
		public string dosing
		{
			get
			{
				return this._dosing;
			}
			set
			{
				if ((this._dosing != value))
				{
					this._dosing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_days", DbType="TinyInt")]
		public System.Nullable<byte> days
		{
			get
			{
				return this._days;
			}
			set
			{
				if ((this._days != value))
				{
					this._days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="SmallInt")]
		public System.Nullable<short> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this._amt = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_CBC_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_CBC_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_DM_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_DM_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_DRUG_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_DRUG_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_hepa_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_hepa_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_OTHER_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_OTHER_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_labdata_UA_by_uidResult
	{
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _o;
		
		public sp_labdata_UA_by_uidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="NVarChar(3999)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this._o = value;
				}
			}
		}
	}
	
	public partial class sp_querytableResult
	{
		
		private long _Query_id;
		
		private string _uid;
		
		private System.Nullable<System.DateTime> _QDATE;
		
		private System.Nullable<bool> _if_cloudmed;
		
		private System.Nullable<bool> _if_schedule;
		
		private System.Nullable<bool> _if_cloudlab;
		
		private string _cname;
		
		private System.Nullable<bool> _OP;
		
		private System.Nullable<bool> _discharge;
		
		private System.Nullable<bool> _rehab;
		
		private System.Nullable<bool> _if_TCM;
		
		private System.Nullable<bool> _if_dental;
		
		private System.Nullable<bool> _if_allergy;
		
		public sp_querytableResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Query_id", DbType="BigInt NOT NULL")]
		public long Query_id
		{
			get
			{
				return this._Query_id;
			}
			set
			{
				if ((this._Query_id != value))
				{
					this._Query_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(20)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> QDATE
		{
			get
			{
				return this._QDATE;
			}
			set
			{
				if ((this._QDATE != value))
				{
					this._QDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_cloudmed", DbType="Bit")]
		public System.Nullable<bool> if_cloudmed
		{
			get
			{
				return this._if_cloudmed;
			}
			set
			{
				if ((this._if_cloudmed != value))
				{
					this._if_cloudmed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_schedule", DbType="Bit")]
		public System.Nullable<bool> if_schedule
		{
			get
			{
				return this._if_schedule;
			}
			set
			{
				if ((this._if_schedule != value))
				{
					this._if_schedule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_cloudlab", DbType="Bit")]
		public System.Nullable<bool> if_cloudlab
		{
			get
			{
				return this._if_cloudlab;
			}
			set
			{
				if ((this._if_cloudlab != value))
				{
					this._if_cloudlab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OP", DbType="Bit")]
		public System.Nullable<bool> OP
		{
			get
			{
				return this._OP;
			}
			set
			{
				if ((this._OP != value))
				{
					this._OP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discharge", DbType="Bit")]
		public System.Nullable<bool> discharge
		{
			get
			{
				return this._discharge;
			}
			set
			{
				if ((this._discharge != value))
				{
					this._discharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rehab", DbType="Bit")]
		public System.Nullable<bool> rehab
		{
			get
			{
				return this._rehab;
			}
			set
			{
				if ((this._rehab != value))
				{
					this._rehab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_TCM", DbType="Bit")]
		public System.Nullable<bool> if_TCM
		{
			get
			{
				return this._if_TCM;
			}
			set
			{
				if ((this._if_TCM != value))
				{
					this._if_TCM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_dental", DbType="Bit")]
		public System.Nullable<bool> if_dental
		{
			get
			{
				return this._if_dental;
			}
			set
			{
				if ((this._if_dental != value))
				{
					this._if_dental = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_if_allergy", DbType="Bit")]
		public System.Nullable<bool> if_allergy
		{
			get
			{
				return this._if_allergy;
			}
			set
			{
				if ((this._if_allergy != value))
				{
					this._if_allergy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
